export type StateConfig = {
  slug: string;
  stateName: string;
  abbreviation: string;
  landlordTerm: string;
  tenantTerm: string;
  exampleCities: string[];
};

export const STATE_CONFIGS: StateConfig[] = [
  {
    slug: "alabama",
    stateName: "Alabama",
    abbreviation: "AL",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Birmingham", "Montgomery", "Huntsville"],
  },
  {
    slug: "alaska",
    stateName: "Alaska",
    abbreviation: "AK",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Anchorage", "Juneau", "Fairbanks"],
  },
  {
    slug: "arizona",
    stateName: "Arizona",
    abbreviation: "AZ",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Phoenix", "Tucson", "Scottsdale"],
  },
  {
    slug: "arkansas",
    stateName: "Arkansas",
    abbreviation: "AR",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Little Rock", "Fayetteville", "Fort Smith"],
  },
  {
    slug: "california",
    stateName: "California",
    abbreviation: "CA",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Los Angeles", "San Diego", "San Francisco"],
  },
  {
    slug: "colorado",
    stateName: "Colorado",
    abbreviation: "CO",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Denver", "Colorado Springs", "Boulder"],
  },
  {
    slug: "connecticut",
    stateName: "Connecticut",
    abbreviation: "CT",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Hartford", "New Haven", "Stamford"],
  },
  {
    slug: "delaware",
    stateName: "Delaware",
    abbreviation: "DE",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Wilmington", "Dover", "Newark"],
  },
  {
    slug: "florida",
    stateName: "Florida",
    abbreviation: "FL",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Miami", "Orlando", "Tampa"],
  },
  {
    slug: "georgia",
    stateName: "Georgia",
    abbreviation: "GA",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Atlanta", "Savannah", "Augusta"],
  },
  {
    slug: "hawaii",
    stateName: "Hawaii",
    abbreviation: "HI",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Honolulu", "Hilo", "Kailua"],
  },
  {
    slug: "idaho",
    stateName: "Idaho",
    abbreviation: "ID",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Boise", "Idaho Falls", "Meridian"],
  },
  {
    slug: "illinois",
    stateName: "Illinois",
    abbreviation: "IL",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Chicago", "Springfield", "Naperville"],
  },
  {
    slug: "indiana",
    stateName: "Indiana",
    abbreviation: "IN",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Indianapolis", "Fort Wayne", "Evansville"],
  },
  {
    slug: "iowa",
    stateName: "Iowa",
    abbreviation: "IA",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Des Moines", "Cedar Rapids", "Iowa City"],
  },
  {
    slug: "kansas",
    stateName: "Kansas",
    abbreviation: "KS",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Wichita", "Topeka", "Overland Park"],
  },
  {
    slug: "kentucky",
    stateName: "Kentucky",
    abbreviation: "KY",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Louisville", "Lexington", "Bowling Green"],
  },
  {
    slug: "louisiana",
    stateName: "Louisiana",
    abbreviation: "LA",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["New Orleans", "Baton Rouge", "Shreveport"],
  },
  {
    slug: "maine",
    stateName: "Maine",
    abbreviation: "ME",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Portland", "Augusta", "Bangor"],
  },
  {
    slug: "maryland",
    stateName: "Maryland",
    abbreviation: "MD",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Baltimore", "Annapolis", "Silver Spring"],
  },
  {
    slug: "massachusetts",
    stateName: "Massachusetts",
    abbreviation: "MA",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Boston", "Cambridge", "Worcester"],
  },
  {
    slug: "michigan",
    stateName: "Michigan",
    abbreviation: "MI",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Detroit", "Grand Rapids", "Ann Arbor"],
  },
  {
    slug: "minnesota",
    stateName: "Minnesota",
    abbreviation: "MN",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Minneapolis", "St. Paul", "Rochester"],
  },
  {
    slug: "mississippi",
    stateName: "Mississippi",
    abbreviation: "MS",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Jackson", "Gulfport", "Biloxi"],
  },
  {
    slug: "missouri",
    stateName: "Missouri",
    abbreviation: "MO",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["St. Louis", "Kansas City", "Springfield"],
  },
  {
    slug: "montana",
    stateName: "Montana",
    abbreviation: "MT",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Billings", "Missoula", "Bozeman"],
  },
  {
    slug: "nebraska",
    stateName: "Nebraska",
    abbreviation: "NE",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Omaha", "Lincoln", "Bellevue"],
  },
  {
    slug: "nevada",
    stateName: "Nevada",
    abbreviation: "NV",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Las Vegas", "Reno", "Henderson"],
  },
  {
    slug: "new-hampshire",
    stateName: "New Hampshire",
    abbreviation: "NH",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Manchester", "Concord", "Nashua"],
  },
  {
    slug: "new-jersey",
    stateName: "New Jersey",
    abbreviation: "NJ",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Newark", "Jersey City", "Trenton"],
  },
  {
    slug: "new-mexico",
    stateName: "New Mexico",
    abbreviation: "NM",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Albuquerque", "Santa Fe", "Las Cruces"],
  },
  {
    slug: "new-york",
    stateName: "New York",
    abbreviation: "NY",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["New York City", "Buffalo", "Rochester"],
  },
  {
    slug: "north-carolina",
    stateName: "North Carolina",
    abbreviation: "NC",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Charlotte", "Raleigh", "Greensboro"],
  },
  {
    slug: "north-dakota",
    stateName: "North Dakota",
    abbreviation: "ND",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Fargo", "Bismarck", "Grand Forks"],
  },
  {
    slug: "ohio",
    stateName: "Ohio",
    abbreviation: "OH",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Columbus", "Cleveland", "Cincinnati"],
  },
  {
    slug: "oklahoma",
    stateName: "Oklahoma",
    abbreviation: "OK",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Oklahoma City", "Tulsa", "Norman"],
  },
  {
    slug: "oregon",
    stateName: "Oregon",
    abbreviation: "OR",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Portland", "Salem", "Eugene"],
  },
  {
    slug: "pennsylvania",
    stateName: "Pennsylvania",
    abbreviation: "PA",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Philadelphia", "Pittsburgh", "Harrisburg"],
  },
  {
    slug: "rhode-island",
    stateName: "Rhode Island",
    abbreviation: "RI",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Providence", "Warwick", "Cranston"],
  },
  {
    slug: "south-carolina",
    stateName: "South Carolina",
    abbreviation: "SC",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Charleston", "Columbia", "Greenville"],
  },
  {
    slug: "south-dakota",
    stateName: "South Dakota",
    abbreviation: "SD",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Sioux Falls", "Rapid City", "Aberdeen"],
  },
  {
    slug: "tennessee",
    stateName: "Tennessee",
    abbreviation: "TN",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Nashville", "Memphis", "Knoxville"],
  },
  {
    slug: "texas",
    stateName: "Texas",
    abbreviation: "TX",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Houston", "Dallas", "Austin"],
  },
  {
    slug: "utah",
    stateName: "Utah",
    abbreviation: "UT",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Salt Lake City", "Provo", "Ogden"],
  },
  {
    slug: "vermont",
    stateName: "Vermont",
    abbreviation: "VT",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Burlington", "Montpelier", "Rutland"],
  },
  {
    slug: "virginia",
    stateName: "Virginia",
    abbreviation: "VA",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Richmond", "Virginia Beach", "Arlington"],
  },
  {
    slug: "washington",
    stateName: "Washington",
    abbreviation: "WA",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Seattle", "Spokane", "Tacoma"],
  },
  {
    slug: "west-virginia",
    stateName: "West Virginia",
    abbreviation: "WV",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Charleston", "Morgantown", "Huntington"],
  },
  {
    slug: "wisconsin",
    stateName: "Wisconsin",
    abbreviation: "WI",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Milwaukee", "Madison", "Green Bay"],
  },
  {
    slug: "wyoming",
    stateName: "Wyoming",
    abbreviation: "WY",
    landlordTerm: "landlord",
    tenantTerm: "tenant",
    exampleCities: ["Cheyenne", "Casper", "Laramie"],
  },
];
