const FALLBACK_TERMS_HTML = `
<h2>Terms of Service</h2>
<p>AI Lease Builder ("we", "us", "our") provides tools that help users draft, format, and export residential lease agreements and related documents. By using this service, you agree to these Terms of Service.</p>
<p>We are not a law firm and do not provide legal advice. All documents generated by this platform should be reviewed by a qualified attorney licensed in the relevant jurisdiction before use.</p>
`;

async function getSettings() {
  const baseUrl =
    process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

  try {
    const res = await fetch(`${baseUrl}/api/admin/settings`, {
      cache: "no-store",
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data;
  } catch {
    return null;
  }
}

export default async function TermsPage() {
  const data = await getSettings();
  const html =
    data?.legal?.termsUrl && data.legal.termsUrl.trim().length > 0
      ? data.legal.termsUrl
      : FALLBACK_TERMS_HTML;

  return (
    <div className="max-w-3xl mx-auto px-4 py-12 text-gray-200">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <div
        className="prose prose-invert max-w-none"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
