const FALLBACK_DISCLAIMER_HTML = `
<h2>Legal Disclaimer</h2>
<p>AI Lease Builder is not a law firm and does not provide legal advice, representation, or services. All content, including any generated lease, addendum, or clause, is provided for informational and drafting assistance purposes only.</p>
<p>Your use of this platform does not create an attorney-client relationship. You should consult a qualified attorney licensed in your jurisdiction before relying on any document generated by this service.</p>
`;

async function getSettings() {
  const baseUrl =
    process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

  try {
    const res = await fetch(`${baseUrl}/api/admin/settings`, {
      cache: "no-store",
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data;
  } catch {
    return null;
  }
}

export default async function DisclaimerPage() {
  const data = await getSettings();
  const html =
    data?.legal?.legalDisclaimer &&
    data.legal.legalDisclaimer.trim().length > 0
      ? data.legal.legalDisclaimer
      : FALLBACK_DISCLAIMER_HTML;

  return (
    <div className="max-w-3xl mx-auto px-4 py-12 text-gray-200">
      <h1 className="text-3xl font-bold mb-6">Legal Disclaimer</h1>
      <div
        className="prose prose-invert max-w-none"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
