// app/faq/page.tsx
"use client";

import { useState } from "react";

type FAQItem = {
  question: string;
  answer: string;
  category: "General" | "Pricing" | "Legal" | "Technical";
};

const faqs: FAQItem[] = [
  {
    category: "General",
    question: "What is AI Lease Builder?",
    answer:
      "AI Lease Builder is a tool that helps landlords and property managers generate state-specific residential lease agreements in minutes. You enter key property and lease details and we generate a structured, professional lease you can download as PDF or DOCX."
  },
  {
    category: "General",
    question: "Which states do you support?",
    answer:
      "We currently support residential leases for all 50 U.S. states and Washington, D.C. The lease language is tailored to each state and is designed to incorporate state-specific clauses and disclosures where appropriate."
  },
  {
    category: "General",
    question: "Can I generate leases in other languages?",
    answer:
      "Yes. You can generate translations of your lease in multiple languages such as Spanish, French, Portuguese, and more. Keep in mind that the legally binding version of the lease is usually the English version, and any translations should be treated as convenience copies."
  },
  {
    category: "Pricing",
    question: "Do I really get a free lease?",
    answer:
      "Yes. You can generate one full English lease completely free — no credit card required. This lets you see the quality of the document before paying for additional leases or multilingual options."
  },
  {
    category: "Pricing",
    question: "When do I have to pay?",
    answer:
      "After you use your free English lease, any additional leases or multilingual generations require a paid plan. Pay-as-you-go is great for occasional use, while Pro and Business plans are better for frequent or higher-volume users."
  },
  {
    category: "Pricing",
    question: "Are multilingual leases included in the free plan?",
    answer:
      "No. The free plan covers one English lease only. To generate leases in other languages (such as Spanish or French), you will need to use a paid plan."
  },
  {
    category: "Legal",
    question: "Is this a substitute for a lawyer?",
    answer:
      "No. AI Lease Builder is a drafting assistant, not a law firm. While we aim to produce high-quality, state-aware lease language, we always recommend that a qualified attorney review your lease before it is signed, especially for complex situations."
  },
  {
    category: "Legal",
    question: "Are the leases legally binding?",
    answer:
      "A lease generated by AI Lease Builder can form part of a legally binding agreement when it is properly executed (signed and dated) by all parties and complies with local laws. However, enforcement ultimately depends on many factors, so it is wise to have important documents reviewed by a licensed attorney."
  },
  {
    category: "Technical",
    question: "What happens to my data?",
    answer:
      "We use your property and lease details only to generate your documents. We do not sell your data. Depending on future product updates, we may store anonymized information to improve template quality, but you will be able to request that your data be deleted."
  },
  {
    category: "Technical",
    question: "Do you store my generated leases?",
    answer:
      "Currently, leases are kept client-side in your browser for immediate download. In future versions, we may add cloud storage so you can re-download prior leases from your account. When that launches, you will have clear controls over what is stored."
  }
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const [activeFilter, setActiveFilter] = useState<
    FAQItem["category"] | "All"
  >("All");

  const categories: (FAQItem["category"] | "All")[] = [
    "All",
    "General",
    "Pricing",
    "Legal",
    "Technical"
  ];

  const filteredFaqs =
    activeFilter === "All"
      ? faqs
      : faqs.filter((faq) => faq.category === activeFilter);

  return (
    <div className="relative min-h-screen bg-[#050816] text-white px-4 py-10">
      {/* Background gradient blobs */}
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -top-24 right-10 h-60 w-60 bg-purple-600/20 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-0 h-64 w-64 bg-blue-500/20 rounded-full blur-3xl" />
      </div>

      <div className="relative max-w-4xl mx-auto">
        <header className="text-center mb-8">
          <h1 className="text-3xl md:text-4xl font-bold">Frequently Asked Questions</h1>
          <p className="text-gray-300 mt-2 text-sm md:text-base">
            Answers to common questions about AI Lease Builder, pricing, and how
            to use the product safely.
          </p>
        </header>

        {/* Category filters */}
        <div className="flex flex-wrap gap-2 justify-center mb-6 text-xs md:text-sm">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => {
                setActiveFilter(cat);
                setOpenIndex(0);
              }}
              className={`px-3 py-1 rounded-full border ${
                activeFilter === cat
                  ? "bg-white text-[#050816] border-white"
                  : "border-white/25 text-gray-300 hover:border-cyan-400 hover:text-white"
              } transition`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* FAQ accordion */}
        <div className="space-y-3">
          {filteredFaqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={faq.question}
                className="border border-white/15 rounded-xl bg-[#0c1127]/90 overflow-hidden"
              >
                <button
                  type="button"
                  onClick={() =>
                    setOpenIndex(isOpen ? null : index)
                  }
                  className="w-full px-4 py-3 flex items-center justify-between text-left"
                >
                  <div>
                    <p className="text-sm md:text-base font-semibold">
                      {faq.question}
                    </p>
                    <p className="text-[11px] text-gray-400 mt-0.5">
                      {faq.category}
                    </p>
                  </div>
                  <span className="text-gray-300 text-xs">
                    {isOpen ? "▲" : "▼"}
                  </span>
                </button>
                {isOpen && (
                  <div className="px-4 pb-4 text-xs md:text-sm text-gray-200 border-t border-white/10">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Contact blurb */}
        <section className="mt-10 text-center text-xs text-gray-400">
          <p>
            Still have questions? Email{" "}
            <a
              href="mailto:support@aileasebuilder.com"
              className="text-cyan-300 hover:text-cyan-200"
            >
              support@aileasebuilder.com
            </a>{" "}
            and we&apos;ll be happy to help.
          </p>
        </section>
      </div>
    </div>
  );
}
