"use client";

import { useState } from "react";
import Script from "next/script";

type FAQItem = {
  question: string;
  answer: string;
  category: "General" | "Pricing" | "Legal" | "Technical";
};

const faqs: FAQItem[] = [
  {
    category: "General",
    question: "What is AI Lease Builder and what does it do?",
    answer:
      "AI Lease Builder is an automated platform that generates state-specific, legally structured residential leases based on the information you provide. Instead of generic templates, it creates a customized, property-specific lease using attorney-style language."
  },
  {
    category: "General",
    question: "Does AI Lease Builder support all 50 states?",
    answer:
      "Yes. The generator supports residential leases for all 50 U.S. states and Washington, D.C., automatically adjusting to your state's disclosures and housing requirements."
  },
  {
    category: "General",
    question: "Can I generate leases in multiple languages?",
    answer:
      "Yes. You can produce translated versions in Spanish, French, Portuguese, Chinese, Arabic, Russian, and more. While translations help with clarity, the English version is typically the legally binding contract."
  },
  {
    category: "Pricing",
    question: "Is the first lease really free?",
    answer:
      `Yes. Your first full English lease is completely free—no credit card required. This allows you to review the structure and wording before purchasing additional leases. You can generate your first lease here: <a href="/generate-lease" class="text-cyan-300 underline-offset-2 hover:underline">Generate Lease</a>.` // ← internal link added
  },
  {
    category: "Pricing",
    question: "How does pricing work?",
    answer:
      "After using your free English lease, each new lease generation costs $8. This flat price applies to both English-only and multilingual leases, making it affordable whether you're a single-property landlord or managing multiple rentals."
  },
  {
    category: "Pricing",
    question: "Are translated leases included in the free plan?",
    answer:
      "No. The free plan covers one English-only lease. Translated leases require payment because each language is generated and formatted separately."
  },
  {
    category: "Legal",
    question: "Is AI Lease Builder a substitute for a lawyer?",
    answer:
      "No. AI Lease Builder is a drafting tool, not a law firm. While it produces attorney-style clauses tuned to your state's requirements, a licensed attorney should review complex or unusual rental situations."
  },
  {
    category: "Legal",
    question: "Are the leases legally binding in my state?",
    answer:
      `A lease generated by AI Lease Builder can serve as a legally binding contract once signed and compliant with your state's laws. Enforcement depends on proper execution and adherence to local regulations. For pricing details, visit the <a href="/pricing" class="text-cyan-300 underline-offset-2 hover:underline">Pricing page</a>.` // ← internal link added
  },
  {
    category: "Technical",
    question: "How is my information used?",
    answer:
      "Your inputs are used solely to generate your documents. We do not sell user data. Future optional features may include improvements based on anonymized patterns, but users will always control what is stored."
  },
  {
    category: "Technical",
    question: "Do you save my generated leases?",
    answer:
      "Currently, all leases are stored only in your browser for immediate download. We may add optional secure cloud storage in future updates so you can re-download past leases anytime."
  }
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((f) => ({
    "@type": "Question",
    name: f.question,
    acceptedAnswer: {
      "@type": "Answer",
      // IMPORTANT: Must include HTML for internal links
      text: f.answer
    }
  }))
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://aileasebuilder.com"
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "FAQ",
      item: "https://aileasebuilder.com/faq"
    }
  ]
};

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const [activeFilter, setActiveFilter] = useState<
    FAQItem["category"] | "All"
  >("All");

  const categories: (FAQItem["category"] | "All")[] = [
    "All",
    "General",
    "Pricing",
    "Legal",
    "Technical"
  ];

  const filteredFaqs =
    activeFilter === "All"
      ? faqs
      : faqs.filter((faq) => faq.category === activeFilter);

  return (
    <div className="relative min-h-screen bg-[#050816] text-white px-4 py-10">
      {/* SEO structured data */}
      <Script
        id="faq-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <Script
        id="breadcrumb-schema"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      {/* Background gradient blobs */}
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -top-24 right-10 h-60 w-60 bg-purple-600/20 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-0 h-64 w-64 bg-blue-500/20 rounded-full blur-3xl" />
      </div>

      <div className="relative max-w-4xl mx-auto">
        <header className="text-center mb-8">
          <h1 className="text-3xl md:text-4xl font-bold">
            Frequently Asked Questions
          </h1>
          <p className="text-gray-300 mt-2 text-sm md:text-base">
            Clear answers about AI Lease Builder, pricing, legal considerations,
            and how the platform works.
          </p>
        </header>

        {/* Category filters */}
        <div className="flex flex-wrap gap-2 justify-center mb-6 text-xs md:text-sm">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => {
                setActiveFilter(cat);
                setOpenIndex(0);
              }}
              className={`px-3 py-1 rounded-full border ${
                activeFilter === cat
                  ? "bg-white text-[#050816] border-white"
                  : "border-white/25 text-gray-300 hover:border-cyan-400 hover:text-white"
              } transition`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* FAQ accordion */}
        <div className="space-y-3">
          {filteredFaqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={faq.question}
                className="border border-white/15 rounded-xl bg-[#0c1127]/90 overflow-hidden"
              >
                <button
                  type="button"
                  onClick={() =>
                    setOpenIndex(isOpen ? null : index)
                  }
                  className="w-full px-4 py-3 flex items-center justify-between text-left"
                >
                  <div>
                    <p className="text-sm md:text-base font-semibold">
                      {faq.question}
                    </p>
                    <p className="text-[11px] text-gray-400 mt-0.5">
                      {faq.category}
                    </p>
                  </div>
                  <span className="text-gray-300 text-xs">
                    {isOpen ? "▲" : "▼"}
                  </span>
                </button>
                {isOpen && (
                  <div
                    className="px-4 pb-4 text-xs md:text-sm text-gray-200 border-t border-white/10"
                    dangerouslySetInnerHTML={{ __html: faq.answer }}
                  />
                )}
              </div>
            );
          })}
        </div>

        {/* Contact blurb */}
        <section className="mt-10 text-center text-xs text-gray-400">
          <p>
            Still have questions? Email{" "}
            <a
              href="mailto:support@aileasebuilder.com"
              className="text-cyan-300 hover:text-cyan-200"
            >
              support@aileasebuilder.com
            </a>{" "}
            and we&apos;ll be happy to help.
          </p>
        </section>
      </div>
    </div>
  );
}
